### ISSUE TITLE
Does not do a thing

### ISSUE THREAD

**Issue by Boy17000** [tjhorner/VillagerGPT#1]
Sadly does not do a thing.

**Comment by tjhorner** [comment]
More details please?

**Comment by Boy17000** [comment]
> More details, please?

I downloaded the plugin, it shows Green in the plugin list.
I can type the command "/ttv" and "/ttvend" 
but as I type "/ttv" it does not do a thing, I still right-clicked a villager(with a profession and one without)
But both times it did not do a thing.

I'm half-ish sure that I used the correct API key i used it from: https://platform.openai.com/account/api-keys
Created a new one and used that one in the config.yml -> "openai-key" its GPT 3.5.

The server version is 1.20.1
Running paper.

**Comment by Boy17000** [comment]
additional info: i was now able to interact with a villager but got this error in console: https://pastebin.com/t9NDd3dX
Seems to also crash my server..

I WAS able to interact with a villager this time after re-doing my api key a few times... i was able to start a chat with a villager but after that it kept waiting and waiting untill it asked me to try again, and server crashed.

**Comment by tjhorner** [comment]
OpenAI is giving you this error:

> You exceeded your current quota, please check your plan and billing details

Make sure you have a credit card set up in your account and that you haven't set up any limits here: https://platform.openai.com/account/billing/limits

If you have a free account, you probably ran out of free tokens. If you've checked both of these things and you're still getting the error, you are probably getting rate limited. You can contact OpenAI support for more help with the error, since I don't have visibility into it

Closing since this isn't an issue with the plugin itself
